/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:97753006-1db3-423f-a4e0-c9a143f99f32",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_VtEJ6PsFn",
    "aws_user_pools_web_client_id": "75qu7cmlufu6hadnaatetghuko",
    "oauth": {}
};
export default awsmobile;